services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: zof
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
