export const theme = {
  ltr: "ltr",
  rtl: "rtl",
  placeholder: "text-gray-400",
  paragraph: "mb-2",
  quote: "border-l-4 border-gray-300 pl-4 italic text-gray-600 my-4",
  heading: {
    h1: "text-3xl font-bold mb-4",
    h2: "text-2xl font-bold mb-3",
    h3: "text-xl font-bold mb-2",
    h4: "text-lg font-bold mb-2",
    h5: "text-base font-bold mb-1",
    h6: "text-sm font-bold mb-1",
  },
  list: {
    nested: {
      listitem: "list-none",
    },
    ol: "list-decimal list-inside mb-2",
    ul: "list-disc list-inside mb-2",
    listitem: "mb-1",
  },
  image: "max-w-full h-auto mx-auto block my-4",
  link: "text-blue-600 hover:text-blue-800 underline",
  text: {
    bold: "font-bold",
    italic: "italic",
    overflowed: "overflow-hidden",
    hashtag: "text-blue-500",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    code: "bg-gray-100 px-1 py-0.5 rounded text-sm font-mono",
    highlight: "bg-yellow-200 px-1 rounded",
  },
  code: "bg-gray-100 p-4 rounded-lg font-mono text-sm overflow-x-auto my-4 leading-loose",
  codeHighlight: {
    atrule: "text-purple-600",
    attr: "text-blue-600",
    boolean: "text-red-600",
    builtin: "text-purple-600",
    cdata: "text-gray-600",
    char: "text-green-600",
    class: "text-blue-600",
    "class-name": "text-blue-600",
    comment: "text-gray-500",
    constant: "text-red-600",
    deleted: "text-red-600",
    doctype: "text-gray-600",
    entity: "text-orange-600",
    function: "text-purple-600",
    important: "text-red-600",
    inserted: "text-green-600",
    keyword: "text-purple-600",
    namespace: "text-blue-600",
    number: "text-red-600",
    operator: "text-gray-700",
    prolog: "text-gray-600",
    property: "text-blue-600",
    punctuation: "text-gray-700",
    regex: "text-green-600",
    selector: "text-green-600",
    string: "text-green-600",
    symbol: "text-red-600",
    tag: "text-red-600",
    url: "text-blue-600",
    variable: "text-orange-600",
  },
  checklist: "list-none",
  "checklist-item": "flex items-center gap-2 mb-1",
};
